import type { KeyObject } from "node:crypto";

import type { SignatureAlgorithm } from "@parmana/shared";

/**
 * Canonical key identifier used when no other keyId is
 * specified. Every Parmana process that signs or verifies
 * with the default key uses this identifier, so key material
 * generated by scripts/generate-keypair.ts is found
 * consistently across the crypto and runtime packages.
 */
export const DEFAULT_KEY_ID = "default";

/**
 * Keyid for the secondary (hybrid-mode) signing key, living alongside
 * DEFAULT_KEY_ID under the same PARMANA_KEY_DIR (Hybrid Signature
 * Support milestone, Phase A). Only read when CRYPTO_MODE=hybrid;
 * generate it with `npm run generate:hybrid-secondary-key`. Deliberately
 * a distinct keyId rather than reusing DEFAULT_KEY_ID -- FileKeyProvider
 * resolves keys purely by keyId (`<keyId>.private.pem`), and one keyId
 * can only ever hold one algorithm's key material at a time.
 */
export const DEFAULT_SECONDARY_KEY_ID = "default-secondary";

/**
 * Signing key metadata.
 */
export interface KeyMetadata {
  readonly keyId: string;

  readonly algorithm: SignatureAlgorithm;
}

/**
 * Key management abstraction.
 */
export interface KeyProvider {
  /**
   * Returns metadata for the specified key.
   */
  getMetadata(
    keyId: string,
  ): Promise<KeyMetadata>;

  /**
   * Returns the private key.
   */
  getPrivateKey(
    keyId: string,
  ): Promise<KeyObject>;

  /**
   * Returns the public key.
   */
  getPublicKey(
    keyId: string,
  ): Promise<KeyObject>;

  /**
   * Returns true if the key exists.
   */
  hasKey(
    keyId: string,
  ): Promise<boolean>;
}