/**
 * Parmana SDK
 *
 * Policy API.
 *
 * Provides access to policy-related Runtime APIs.
 *
 * Responsibilities:
 * - Validate policies.
 * - Retrieve policy information.
 *
 * This API does NOT:
 * - execute transactions
 * - authorize execution
 * - verify trust records
 * - replay executions
 */

import type {
  Policy,
} from "@parmana/policy";

import type {
  Transport,
} from "../config/Transport.js";

/**
 * Canonical policy validation result.
 */
export interface PolicyValidationResult {
  /**
   * Indicates whether the policy is valid.
   */
  readonly valid: boolean;

  /**
   * Validation errors.
   */
  readonly errors: readonly string[];
}

/**
 * Policy API.
 */
export class PolicyApi {
  constructor(
    private readonly transport: Transport,
  ) {}

  /**
   * Validates a policy.
   *
   * POST /policies/validate does not use the shared {error, code?}
   * envelope for 400 or 404: both are {valid, errors}, its own shape,
   * the caller's answer, not an SDK-level failure — so those two
   * statuses are exempted from the default throw-on-error behavior. 401
   * is not exempted: it is generated by caller-auth middleware before
   * this route's own handler ever runs, and does use the shared
   * envelope, identically to every other route. See
   * /api-reference/error-handling.
   */
  public async validate(
    policy: Policy,
  ): Promise<PolicyValidationResult> {
    const response =
      await this.transport.send<PolicyValidationResult>({
        path: "/policies/validate",

        method: "POST",

        body: policy,

        nonThrowingStatuses: [400, 404],
      });

    return response.body;
  }
}