/**
 * Parmana SDK
 *
 * Canonical transport abstraction.
 *
 * A Transport is responsible only for sending requests
 * to the Parmana Runtime and returning responses.
 *
 * It does NOT:
 * - evaluate policy
 * - authorize execution
 * - perform verification
 * - perform replay
 * - implement business logic
 */

/**
 * Transport request.
 */
export interface TransportRequest {
  /**
   * Relative API path.
   *
   * Example:
   * /execute
   */
  readonly path: string;

  /**
   * HTTP method.
   */
  readonly method:
    | "GET"
    | "POST"
    | "PUT"
    | "PATCH"
    | "DELETE";

  /**
   * Optional request body.
   */
  readonly body?: unknown;

  /**
   * Optional request headers.
   */
  readonly headers?: Readonly<Record<string, string>>;

  /**
   * HTTP status codes that must be returned as an ordinary
   * TransportResponse instead of being mapped to a thrown ParmanaError
   * subclass, because this specific route's response body at that
   * specific status is not the shared {error, code?} envelope.
   *
   * Default: none (every status >= 400 throws). Today exactly one route
   * needs this: POST /policies/validate returns {valid, errors} — not
   * {error, code?} — at 400 and 404 (but the shared envelope still
   * applies to 401, generated by caller-auth middleware before this
   * route's own handler ever runs). See PolicyApi.validate and
   * /api-reference/error-handling.
   */
  readonly nonThrowingStatuses?: readonly number[];
}

/**
 * Transport response.
 */
export interface TransportResponse<T = unknown> {
  /**
   * HTTP status code.
   */
  readonly status: number;

  /**
   * Response headers.
   */
  readonly headers: Readonly<Record<string, string>>;

  /**
   * Response body.
   */
  readonly body: T;
}

/**
 * Canonical SDK transport.
 */
export interface Transport {
  /**
   * Sends a request to the Parmana Runtime.
   */
  send<T = unknown>(
    request: TransportRequest,
  ): Promise<TransportResponse<T>>;
}