import { Decision } from "./decision.js";
import { ExecutionEvidence } from "./execution-evidence.js";
import { ExecutionMetadata } from "./execution-metadata.js";

/**
 * Parmana Trust Core
 *
 * Execution
 *
 * Records what actually happened while processing a
 * Business Transaction.
 *
 * Every Execution records exactly one immutable
 * Decision produced by deterministic Policy
 * evaluation.
 *
 * Executions are immutable trust artifacts and
 * become part of the Execution Trust Record.
 */
export interface Execution {
  /**
   * Unique Execution identifier.
   */
  readonly executionId: string;

  /**
   * Business Transaction to which this Execution belongs.
   */
  readonly businessTransactionId: string;

  /**
   * Immutable Decision produced by this Execution.
   *
   * The Decision is generated by evaluating the
   * referenced Policy against the supplied runtime
   * signals.
   */
  readonly decision: Decision;

  /**
   * Execution lifecycle state.
   */
  readonly status: ExecutionStatus;

  /**
   * Execution mode.
   */
  readonly mode: ExecutionMode;

  /**
   * UTC timestamp when execution started.
   */
  readonly startedAt: Date;

  /**
   * UTC timestamp when execution completed.
   *
   * Present only for terminal executions.
   */
  readonly completedAt?: Date;

  /**
   * Immutable execution evidence.
   */
  readonly evidence?: ExecutionEvidence;

  /**
   * Execution-specific metadata.
   */
  readonly metadata?: ExecutionMetadata;
}

/**
 * Canonical execution lifecycle.
 */
export enum ExecutionStatus {
  PROCESSING = "PROCESSING",

  COMPLETED = "COMPLETED",

  FAILED = "FAILED",
}

/**
 * Execution mode.
 */
export enum ExecutionMode {
  SYNC = "SYNC",

  ASYNC = "ASYNC",
}